data:
  path: "data/instruct"
  json_path: "${data.path}/hindi_instruct_conversations.json"
  validation_split: 0.05
  train_fraction: 1.0
  val_fraction: 1.0
  seed: 42
  num_workers: 4

model:
  name: "llama"
  path: "models/llama"
  config_path: "models/llama"
  model_base: "models/llama"
  tokenizer_path: "models/llama"
  model_max_length: 2048

training:
  num_train_epochs: 3
  batch_size: 3 #!keep this
  gradient_accumulation_steps: 7  #forward and backward are accumulated over this steps and then the gradients are updated(sum of 8 microbatch)
  learning_rate: 0.000107467137359001
  tune_speech_projector: false
  tune_llm_backbone: true
  tune_speech_encoder: false
  use_lora: true
  lora_r: 128  #128
  lora_alpha: 64  #64
  lora_dropout: 0.05
  gradient_checkpointing: true
  use_8bit_optimizer: false
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.03
  weight_decay: 0.0
  max_grad_norm: 1.0   #clipping the gradients to prevent exploding gradients
  precision: "bf16-mixed"
  accelerator: "auto"
  devices: "auto"
  strategy: "auto"
  log_every_n_steps: 10
  val_check_interval: 0.25
  fast_dev_run: false
  attn_implementation: "sdpa"

logging:
  output_dir: "outputs/backbone_lora"
  log_file: "logs/train.log"
  csv: true
  csv_metrics_file: "csv/metrics.csv"
  tensorboard: false
  wandb: true
  wandb_project: "hindi_llama_omni"
  wandb_run_name: "hindi-backbone-lora"
  checkpoint_monitor: "val_loss"
  checkpoint_format: "safetensors"
  save_top_k: 1
  save_last: true
  save_weights_only: true

hydra:
  run:
    dir: ${logging.output_dir}/hydra/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${logging.output_dir}/hydra_sweeps
    subdir: ${hydra.job.num}
